### ISSUE TITLE
Non-unique XML names

### ISSUE THREAD

**Issue by DaTeL237** [hultqvist/ProtoBuf#11]
XmlSerializer cannot always be created with the generated System.Serializable attributes.

An InvalidOperationException is raised when creating an XmlSerializer with an inner exception with message:
> {"Types 'Example.MessageTwo.SubType' and 'Example.MessageOne.SubType' both use the XML type name, 'SubType', from namespace ''. Use XML attributes to specify a unique XML name and/or namespace for the type."}

The following .proto definition and C# code reproduce the exception:

.proto definition:
```
message MessageOne {  
  enum SubType {
    typeOneA = 1;
    typeOneB = 2;
  }

  optional SubType subType = 1;
}

message MessageTwo {
  enum SubType {
    typeTwoA = 1;
    typeTwoB = 2;
  }

  optional SubType subType = 1;
}
```

C# code:
```
using System;
using System.Xml;
using Example; // This is where my generated code went

namespace SerializeTest
{
    public class SerializeTest
    {
        [STAThread]
        static void Main(string[] args)
        {
            Type[] types = new Type[] { typeof(MessageOne), typeof(MessageTwo) };
            var serializer = new System.Xml.Serialization.XmlSerializer(typeof(string), types);
        }
    }
}
```

**Comment by hultqvist** [comment]
I won't work on this myself but if anyone else starts working to fix this I will help to integrate it into working code.
