### ISSUE TITLE
Mono for Android: System.NotSupportedException

### ISSUE THREAD

**Issue by canab** [hultqvist/ProtoBuf#26]
Stream.position is not supported for android asset streams

stacktrace:
at Android.Runtime.InputStreamInvoker.get_Position ()
at ActionLib.Proto.T_Sprite.DeserializeLengthDelimited (System.IO.Stream stream, ActionLib.Proto.T_Sprite instance)

line:
stream.Position

binary:
ProtoBuf-2014-08-23-bin.zip

**Comment by hultqvist** [comment]
There is a wrapper class included in the ProtocolParser.cs file called PositionStream(or StreamRead in older versions) use that to wrap whatever stream that does not support the position attribute.

**Comment by canab** [comment]
Thanks, it works.
