### ISSUE TITLE
Immutable classes and Builders

### ISSUE THREAD

**Issue by R2D221** [hultqvist/ProtoBuf#32]
The original ProtoBuf implementation generates immutable classes, as well as Builders that are mutable version of those classes. It would be nice to have this behavior reflected here too.

**Comment by hultqvist** [comment]
Could you give a code sample on how it would be used.
I'm looking for a subset of the features that would be interesting to have rather than trying to copy the entire API of the other implementations.

**Comment by udgeenbr** [comment]
Hi! I'm using your implementation. Thank you for excellent work! 
My team ported android java game to unity c# last year. There were to much usages of builders, so I have had to implement some builders support to make the work more easy.
Than, builder style has quite an elegant way to set several values at once:
ProtoClass proto = ProtoClass.newBuilder()
                                   .setValueOne(firstValue)
                                   .setValueTwo(secondValue)
                                   .build();

**Comment by Waty** [comment]
I don't see how 

    ProtoClass proto = ProtoClass.newBuilder()
    .setValueOne(firstValue)
    .setValueTwo(secondValue)
    .build();

is more elegant then
```
ProtoClass proto = new ProtoClass { ValueOne = firstValue, ValueTwo = secondValue };
```

but that might be because I'm not used to the Java syntax

**Comment by R2D221** [comment]
>rather than trying to copy the entire API

I think copying the entire API is the best option possible, for interoperability with existing Java code. Of course it can be enhanced with C#-specific syntax, but still maintaining the `Builder` classes.

----

>I don't see how [Java fluent syntax] is more elegant then [C# object initializer]

The problem is not the different in syntax, but the problem in the classes themselves.

The C# builder should be implemented the following way:

    var proto = new ProtoClass.Builder { ValueOne = firstValue, ValueTwo = secondValue };

And then, when you're done, do something like

    var immutableProto = proto.Build();

You don't give up the clearer C# syntax, but still maintain the Builder concept.

**Comment by hultqvist** [comment]
I can see this becoming an optional feature within the generator. How it will end up and who will write it is still up for discussion(well, I will still consider a pull request regardless of the discussion).

I think these kind of discussions are not the best to be had in a github issue.
Therefore I've created a discourse forum at [discuss.silentorbit.com](1).
The idea is to keep bugs and pull requests to github and the rest to the forum where people can use other accounts than github to login.

Also I'm gladly accepting feedback on any other channels for discussion, I've considered a mailing list and someone mentioned an IRC group(though I wouldn't be there to help answering questions).
Send them to [discuss.silentorbit.com](1) or email me at hultqvist@silentorbit.com

 [1]: https://discuss.silentorbit.com/c/protobuf
