### ISSUE TITLE
Compatibility with Visual Studio 2015 tech preview

### ISSUE THREAD

**Issue by langboost** [hultqvist/ProtoBuf#34]
Hello,

I'm excited about this tool. Great work so far! When I try to use it in Windows 10 tech preview, there are some problems. I'd like to help you resolve those before this stuff gets released in late July.

Using this .proto file
https://github.com/WhisperSystems/libaxolotl-java/blob/master/protobuf/WhisperTextProtocol.proto

I discovered 4 errors that seem to be related to compatibility with what namespaces are availalbe from Windows Universal C# class libraries in Windows 10.

There were four distinct bugs found in VS 2015 tech preview when generating. We need to help this community fix their tool.

1) Streams apparently no longer have a close method. This is news to me, so maybe some deeper digging is needed.

Severity	Code	Description	Project	File	Line
Error	CS0117	'Stream' does not contain a definition for 'Close'	libaxolotl-classlib	C:\Users\Jeff\Source\Repos\libaxolotl-windows\libaxolotl-classlib\Protobuf\ProtocolParser.cs	185

2) Encoding.GetString changed in VS 2015

Severity	Code	Description	Project	File	Line
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'index' of 'Encoding.GetString(byte[], int, int)'	libaxolotl-classlib	C:\Users\Jeff\Source\Repos\libaxolotl-windows\libaxolotl-classlib\Protobuf\ProtocolParser.cs	16

3) No Serializable type. I researched this one some. This may be the solution: http://stackoverflow.com/questions/26269025/xml-serialization-error-on-universal-store-app

Severity	Code	Description	Project	File	Line
Error	CS0234	The type or namespace name 'Serializable' does not exist in the namespace 'System' (are you missing an assembly reference?)	libaxolotl-classlib	C:\Users\Jeff\Source\Repos\libaxolotl-windows\libaxolotl-classlib\Protobuf\WhisperTextProtocol.Serializer.cs	787

4) No ApplicationException in Universal C# class libraries. For now, I will just generate my own.

Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'ApplicationException' could not be found (are you missing a using directive or an assembly reference?)	libaxolotl-classlib	C:\Users\Jeff\Source\Repos\libaxolotl-windows\libaxolotl-classlib\Protobuf\ProtocolParser.cs	653

**Comment by hultqvist** [comment]
That was a great find, please make sure all works now.

**Comment by langboost** [comment]
Great, thanks! Let me do some testing and get back to you.
