### ISSUE TITLE
Partial declarations of [CLASS NAME] have conflicting accessibility modifiers

### ISSUE THREAD

**Issue by BamX** [hultqvist/ProtoBuf#36]
[CLASS NAME].partial.cs provided with internal modifier, but other parts is public. What I should do with  this problem? I don't want to edit them manually every time.

**Comment by hultqvist** [comment]
In your .proto file you can add this comment before each message

    //:access=internal
    message ClassName
    {
        ....

**Comment by BamX** [comment]
Thank you!
