### ISSUE TITLE
SerializeLenghtDelimited

### ISSUE THREAD

**Issue by bhe3aiihoctb** [hultqvist/protobuf#46]
Stream.Position not works for NetworkStream

**Comment by hultqvist** [comment]
Use the [PositionStream](https://github.com/hultqvist/protobuf/blob/d67a6d79d0b990f98244a5fb9dfd25da0e14729a/TestProgram/Generated/ProtocolParser.cs#L83) wrapper.
It's included in the [generated code](https://github.com/hultqvist/protobuf/blob/d67a6d79d0b990f98244a5fb9dfd25da0e14729a/TestProgram/Generated/ProtocolParser.cs#L83).

> ProtoBuf.Serializer.Deserialize<NetAddressBook>(new **PositionStream**(networkStream));

**Comment by hultqvist** [comment]
I hope this solved your problem.
