### ISSUE TITLE
proto3 schema not supported?

### ISSUE THREAD

**Issue by mviranyi** [hultqvist/protobuf#49]
I've cloned master and built the CodeGenerator.

First thing is that it can't handle Java specific options:  
`option java_outer_classname = "foobar";`  
But it seems it just gives a warning and proceeds with the compiling:  
`Warning: Unknown option: java_outer_classname`

And after that it expects proto2 field descriptors such as `optional` / `required`.  
Does the compiler take the syntax field into account?? `syntax = "proto3";`

`.proto(6,12): error CS001: unknown rule: string`

Is there a special flag that needs to be set in order to get it to compile proto3 definitions?

**Comment by hultqvist** [comment]
You're correct, support for java options is not implemented, but any unknown options are ignored with a warning.

This implementation is for proto2 so proto3 are not available.
