### ISSUE TITLE
Missing CommandLine 

### ISSUE THREAD

**Issue by EgoSumNemo** [hultqvist/protobuf#50]
I am missing in the references the CommandLine

**Comment by hultqvist** [comment]
It's in a submodule.

    git clone --recurse-submodules https://github.com/hultqvist/protobuf.git

or once you already cloned the main repo

    git submodule init
    git submodule update

**Comment by EgoSumNemo** [comment]
Mate, I cant find it, Excuse my Stupidity I am a Beginner.

**Comment by hultqvist** [comment]
Hi @EgoSumNemo I take it you didn't clone it using git but downloaded a zip from the website.

In that case you can see the `commandline` folder looking somewhat [different on the code page](https://github.com/hultqvist/protobuf).

You can click that folder to get to the commandline repo and from there click the [download button](https://github.com/gsscoder/commandline/archive/e00dd9f0863104cd6dba73c549db3c50eb23f732.zip).

Good luck

**Comment by deitry** [comment]
I guess it's not just me. There is no `.gitmodules` in the repo so git do not see any submodule

**Comment by hultqvist** [comment]
It was since removed.
Not it's back with #52 not as a submodule but as a NuGet package.
